FROM python:latest
COPY iptv-threaded-scanner.py /bin/iptv/iptv-threaded-scanner.py
COPY requirements.txt /bin/iptv/requirements.txt
COPY input-playlist.m3u /bin/iptv/input-playlist.m3u
ADD cronfile /etc/cron.d/iptv-cron
RUN touch /var/log/cron.log
RUN chmod 0644 /etc/cron.d/iptv-cron
RUN chmod -R +x /bin/iptv
RUN apt-get update -y
RUN apt-get -y install cron vim python3-pip 
RUN pip install --requirement /bin/iptv/requirements.txt
CMD cron && tail -f /var/log/cron.log
