version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
